import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const companies = [
  { name: 'Elektroprivreda Republike Srpske', slug: 'elektroprivreda-republike-srpske', jib: '4400000010001', city: 'Trebinje', industry: 'Energetika', revenue: 980000000, profit: 42000000, employees: 8200 },
  { name: 'M:tel a.d. Banja Luka', slug: 'mtel-banja-luka', jib: '4400964000002', city: 'Banja Luka', industry: 'Telekomunikacije', revenue: 520000000, profit: 83000000, employees: 2100 },
  { name: 'Integral Inženjering a.d.', slug: 'integral-inzenjering', jib: '4400999000003', city: 'Laktaši', industry: 'Građevinarstvo', revenue: 240000000, profit: 18000000, employees: 950 },
  { name: 'Lanaco d.o.o.', slug: 'lanaco', jib: '4401200000004', city: 'Banja Luka', industry: 'Informacione tehnologije', revenue: 68000000, profit: 9200000, employees: 330 }
];
async function main() { for (const c of companies) { const industry = await prisma.industry.upsert({ where: { naceCode: c.industry.slice(0, 4).toUpperCase() }, update: {}, create: { naceCode: c.industry.slice(0, 4).toUpperCase(), name: c.industry } }); await prisma.company.upsert({ where: { jib: c.jib }, update: {}, create: { name: c.name, slug: c.slug, jib: c.jib, status: 'ACTIVE', revenue: c.revenue, profit: c.profit, employeeCount: c.employees, averageSalary: 1800, ebitda: c.profit * 1.25, profitMargin: c.profit / c.revenue, debtRatio: 0.31, website: 'https://example.com', industryId: industry.id, address: { create: { city: c.city, street: 'Glavna 1' } }, financialReports: { create: [2021, 2022, 2023, 2024].map((year, i) => ({ year, revenue: c.revenue * (0.82 + i * 0.06), profit: c.profit * (0.75 + i * 0.08), source: 'Seed dataset' })) }, owners: { create: [{ name: 'Akcionari / vlasnici', ownershipPercent: 100 }] }, beneficialOwners: { create: [{ name: 'Dostupno nakon verifikacije registra', controlType: 'UNKNOWN' }] }, employeeStats: { create: [2021, 2022, 2023, 2024].map((year, i) => ({ year, count: Math.round(c.employees * (0.9 + i * 0.03)), source: 'Seed dataset' })) }, salaryStats: { create: [2021, 2022, 2023, 2024].map((year, i) => ({ year, averageGross: 1700 + i * 120, averageNet: 1150 + i * 80, source: 'Seed dataset' })) } } }); } }
main().finally(() => prisma.$disconnect());
